### ISSUE TITLE
Axis of screen resolution are switched

### ISSUE THREAD

**Issue by leongroesch** [JUMO-GmbH-Co-KG/embedded-compositor#27]
The results of `QGuiApplication::primaryScreen()->size()` fetched by a compositor client are dependent on the screen size of the **previous** orientation.
As an result the axis are switched if the screen orientation has changed.

For example on a 1280x800 screen with a 0° orientation the function `QGuiApplication::primaryScreen()->size()` will initially return the correct result of (1280, 800).
If the orientation is changed to 90° the `size()` function will still return (1280, 800) as resolution. When the screen orientation is switched back to 0° the `size` function will return the resolution of a portrait mode (800, 1280).

**Comment by ChHapp** [comment]
This issue is resolved by a qtwayland patch - it seemed that the sendDone event was not being sent correctly. See here, for the full description (https://codereview.qt-project.org/c/qt/qtwayland/+/540389)
